apiVersion: v1
kind: Service
metadata:
  name: "{{ trimSuffix .Values.SUFFIX .Chart.Name }}"
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: frontend