apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  type: nodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000
    protocol: TCP
    name: https
  selector:
    app: frontend